openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/v1/auth/users/:
    get:
      operationId: listListUsers
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
  /api/v1/auth/registration/:
    post:
      operationId: CreateRegistration
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
  /api/v1/auth/login/:
    post:
      operationId: CreateLogin
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''