---
swagger: "2.0"
info:
  description: Описание АИП Uniteams
  version: "1"
  title: Uniteams API
host: 127.0.0.1:8000
basePath: /api/v1/

produces:
  - application/json
components:
  securitySchemes:
    Token:
      type: http
      scheme: apiKey
      in: header
      name: Authorization

paths:

  /auth/users:
    get:
      tags:
        - name: Auth
      summary: Получаем список пользователей
      parameters:
        - name: Authorization
          in: header
          description: Токен администратора
          required: true

          schema:
            type: object
            $ref: '#/definitions/Token'

      security:
        - Token: []
      responses:
        200:
          description: Возвращает список пользователей
          schema:
            $ref: '#/definitions/UsersArray'
        400:
          description: Выборка пуста
        401:
          description: Доступ запрещён
  /auth/login:
    post:
      tags:
        - name: Auth
      summary: Авторизация пользователя
      consumes:
        - application/json
      parameters:
        - in: body
          name: user
          description: Пользователь.
          schema:
            type: object
            required:
              - username
            properties:
              username:
                type: string
              password:
                type: string
      security:
        - ApiKeyAuth: []
      responses:
        200:
          description: Пользователь авторизирован
          schema:
            $ref: '#/definitions/Token'
        401:
          description: Пользователь не авторизован
  /auth/registration:
    post:
      tags:
        - name: Auth
      summary: Регистрация пользователя
      consumes:
        - application/json
      parameters:
        - in: body
          name: user
          description: Пользователь.
          schema:
            type: object
            required:
              - username
            properties:
              username:
                type: string
              email:
                type: string
              password:
                type: string
              retryPassword:
                type: string
      responses:
        200:
          description: Регистрация успешна
          schema:
            $ref: '#/definitions/User'
        403:
          description: Логин занят, регистрация невозможна
  /auth/user/{id}:
    get:
      tags:
        - name: Auth
      summary: Получаем профиль пользователя по ID
      parameters:
        - name: id
          in: path
          description: ID потльзователя
          required: true
          type: integer
          minimum: 1
      responses:
        200:
          description: Профиль пользователя
          schema:
            $ref: '#/definitions/UserProfile'
        403:
          description: Профиль пользователя недоступен
          schema:
            $ref: '#/definitions/ErrorMsg'
    put:
      tags:
        - name: Auth
      summary: Обновляем поля пользователя
      parameters:
        - name: id
          in: path
          description: ID пользователя
          required: true
          type: integer
          minimum: 1
      responses:
        200:
          description: Профиль пользователя обновлён
        403:
          description: Нет прав на изменение профиля
          schema:
            $ref: '#/definitions/ErrorMsg'
definitions:
  User:
    type: object
    required:
      - username
      - email
    properties:
      id:
        type: integer
        example: 123
        description: Уникальный ID пользователя
      username:
        type: string
        example: mybestlogin
        description: Уникальный логин пользователя
      email:
        type: string
        example: myname@favoritemail.org
        description: Email пользователя

  UserProfile:
    type: object
    required:
      - userId
    properties:
      userId:
        type: integer
        example: 123
        description: Уникальный ID пользователя
      firstName:
        type: string
        example: Гордон
        description: Имя в профиле
      lastName:
        type: string
        example: Фримен
        description: Фамилия в профиле
      middleName:
        type: string
        example: Хедкрабович
        description: Отчество в профиле
      gender:
        type: string
        example: Муж
        description: Отчество в профиле
      position:
        type: string
        example: Инженер элементарных частиц
        description: Должность в профиле
  UsersArray:
    type: array
    items:
      $ref: '#/definitions/User'

  Token:
    type: object
    required:
      - Token
    properties:
      Token:
        type: string
        example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MDI5NjUzMjh9.R52zWTcjK5_MsAfthxXSGdjGIYu6Iq5Rj3ckjFJYFqs
  ErrorMsg:
    type: object
    properties:
      msg:
        type: string
        example: Доступ запрещён
        description: Исключение сервера или ограничние прав доступа

