---
swagger: "2.0"
info:
  description: Описание АИП Uniteams
  version: "1"
  title: Uniteams API
host: 127.0.0.1:8000
basePath: /api/v1/

produces:
  - application/json
components:
  securitySchemes:
    Token:
      type: http
      scheme: apiKey
      in: header
      name: Authorization

paths:
  /users/:
    get:
      tags:
        - name: Auth
      summary: Получаем список пользователей
      parameters:
        - name: Authorization
          in: header
          description: Токен администратора
          required: true
          schema:
            type: object
            $ref: '#/definitions/Token'
      security:
        - Token: []
      responses:
        200:
          description: Возвращает список пользователей
          schema:
            $ref: '#/definitions/UsersArray'
        400:
          description: Выборка пуста
        401:
          description: Доступ запрещён
    post:
      tags:
        - name: Auth
      summary: Регистрация пользователя
      consumes:
        - application/json
      parameters:
        - in: body
          name: user
          description: Пользователь.
          schema:
            type: object
            required:
              - username
            properties:
              username:
                type: string
              email:
                type: string
              password:
                type: string
      responses:
        200:
          description: Регистрация успешна
          schema:
            $ref: '#/definitions/User'
        403:
          description: Логин занят, регистрация невозможна
          schema:
            $ref: '#/definitions/ErrorMsg'
  /token/:
    post:
      tags:
        - name: Auth
      summary: Авторизация пользователя
      consumes:
        - application/json
      parameters:
        - in: body
          name: user
          description: Пользователь.
          schema:
            type: object
            required:
              - username
            properties:
              username:
                type: string
              password:
                type: string
      security:
        - ApiKeyAuth: []
      responses:
        200:
          description: Пользователь авторизирован
          schema:
            $ref: '#/definitions/Token'
        401:
          description: Пользователь не авторизован

  /verification/:
    get:
      tags:
        - name: Auth
      summary: Проверка кода активации и активация пользователя
      consumes:
        - application/json
      parameters:
        - name: email
          in: query
          description: Электронная почта пользователя.
          required: true
          type: string
        - name: activation_key
          in: query
          description: Код активации.
          required: true
          type: string

      responses:
        200:
          description: Активация успешна
        402:
          description: Неверный адрес электронной почты или код активации
          schema:
            $ref: '#/definitions/ErrorMsg'
  /users/{id}:
    get:
      tags:
        - name: Auth
      summary: Получаем профиль пользователя по ID
      parameters:
        - name: Authorization
          in: header
          description: Токен пользователя
          required: true
          schema:
            type: object
            $ref: '#/definitions/Token'
        - name: id
          in: path
          description: ID пользователя
          required: true
          type: integer
          minimum: 1
      security:
        - Token: []
      responses:
        200:
          description: Профиль пользователя
          schema:
            $ref: '#/definitions/UserProfile'
        403:
          description: Профиль пользователя недоступен
          schema:
            $ref: '#/definitions/ErrorMsg'
    put:
      tags:
        - name: Auth
      summary: Обновляем поля пользователя
      parameters:
        - name: Authorization
          in: header
          description: Токен пользователя
          required: true
          schema:
            type: object
            $ref: '#/definitions/Token'
        - name: id
          in: path
          description: ID пользователя
          required: true
          type: integer
          minimum: 1
        - name: user_profile
          in: body
          description: Профиль пользователя
          schema:
            type: object
            $ref: '#/definitions/UserProfile'
      security:
        - Token: []
      responses:
        200:
          description: Профиль пользователя обновлён
        403:
          description: Нет прав на изменение профиля
          schema:
            $ref: '#/definitions/ErrorMsg'
  /companies/:
    get:
      tags:
        - name: Auth
      summary: Получаем список компаний
      parameters:
        - name: Authorization
          in: header
          description: Токен администратора
          required: true
          schema:
            type: object
            $ref: '#/definitions/Token'
      security:
        - Token: []
      responses:
        200:
          description: Возвращает список компание
          schema:
            $ref: '#/definitions/СompaniesArray'
        400:
          description: Выборка пуста
        401:
          description: Доступ запрещён
    post:
      tags:
        - name: Auth
      summary: Регистрация компании
      consumes:
        - application/json
      security:
        - Token: []
      parameters:
        - name: Authorization
          in: header
          description: Токен администратора
          required: true
          schema:
            type: object
            $ref: '#/definitions/Token'
        - in: body
          name: company
          description: Компания.
          schema:
            type: object
            required:
              - company_name
            properties:
              company_name:
                type: string
      responses:
        200:
          description: Компания зарегистрирована
          schema:
            $ref: '#/definitions/User'
        403:
          description: Имя компании занято, регистрация компании невозможна
          schema:
            $ref: '#/definitions/ErrorMsg'
  /companies/{id}:
    get:
      tags:
        - name: Auth
      summary: Получаем профиль компании по ID
      parameters:
        - name: Authorization
          in: header
          description: Токен пользователя
          required: true
          schema:
            type: object
            $ref: '#/definitions/Token'
        - name: pk
          in: path
          description: ID компании
          required: true
          type: integer
          minimum: 1
      security:
        - Token: []
      responses:
        200:
          description: Профиль компании
          schema:
            $ref: '#/definitions/Company'
        403:
          description: Профиль компании недоступен
          schema:
            $ref: '#/definitions/ErrorMsg'
    put:
      tags:
        - name: Auth
      summary: Обновляем поля компании
      parameters:
        - name: Authorization
          in: header
          description: Токен пользователя
          required: true
          schema:
            type: object
            $ref: '#/definitions/Token'
        - name: pk
          in: path
          description: ID компании
          required: true
          type: integer
          minimum: 1
        - name: owner
          in: body
          description: Имя пользователя владельца компании
          type: string
        - name: administrator
          in: body
          description: Имя пользователя администратора компании
          type: string
      security:
        - Token: []
      responses:
        200:
          description: Профиль пользователя обновлён
        403:
          description: Нет прав на изменение профиля
          schema:
            $ref: '#/definitions/ErrorMsg'
definitions:
  Company:
    type: object
    requied:
      - company_name
    properties:
      company_name:
        type: string
        example: ООО "Ромашка"
        description: Имя компании
      owner:
        type: object
        description: Владелец компании
        $ref: '#/definitions/User'
      administrator:
        type: object
        description: Администратор компании
        $ref: '#/definitions/User'
      employees:
        type: array
        description: Сотрудники компании
        $ref: '#/definitions/UsersArray'
  СompaniesArray:
    type: array
    items:
      $ref: '#/definitions/Company'
  User:
    type: object
    required:
      - username
      - email
    properties:
      id:
        type: integer
        example: 123
        description: Уникальный ID пользователя
      username:
        type: string
        example: mybestlogin
        description: Уникальный логин пользователя
      email:
        type: string
        example: myname@favoritemail.org
        description: Email пользователя

  UserProfile:
    type: object
    required:
      - userId
    properties:
      first_name:
        type: string
        example: Гордон
        description: Имя в профиле
      last_name:
        type: string
        example: Фримен
        description: Фамилия в профиле
      middle_name:
        type: string
        example: Хедкрабович
        description: Отчество в профиле
      gender:
        type: integer
        example: 1
        description: Пол (1 - Мужской, 2 - Женский)
      position:
        type: string
        example: Инженер элементарных частиц
        description: Должность в профиле
  UsersArray:
    type: array
    items:
      $ref: '#/definitions/User'
  ActivationData:
    type: object
    required:
      - activation_key
      - email
    properties:
      activation_key:
        type: string
        example: LCJleHAiOjE2MDI5NjUzMjh9.R52zWTcjK5_MsAfthxXSGd
        description: Уникальный код активации пользователя
      email:
        type: string
        example: mail@mail.ru
        description: Адресс электронной почты пользователя
  Token:
    type: object
    required:
      - Token
    properties:
      Token:
        type: string
        example: token eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MDI5NjUzMjh9.R52zWTcjK5_MsAfthxXSGdjGIYu6Iq5Rj3ckjFJYFqs


  ErrorMsg:
    type: object
    properties:
      msg:
        type: string
        example: Доступ запрещён
        description: Исключение сервера или ограничние прав доступа

